# Statistics

1 human = 5.6ft

1 coconut = 200ft

average/mean = 102.8(Arithmetic mean)

# Mean & its type:

  1>Arithmetic mean
    
  2>Geometric mean

  3>Harmonic mean

In [1]:
(92+92+92+92+92)/5     #average/arithmetic mean

92.0

In [2]:
import math
math.sqrt(5.6*200*140)

395.9797974644666

In [3]:
(5.6+200+230)/3

145.20000000000002

In [4]:
(5.6*200*230*320)**(1/4)

95.28487295384882

In [5]:
(5.6+200+230+320)/4

188.9

In [6]:
import statistics as s

In [7]:
# restra A
s.geometric_mean((3,80))    #(rating,reviews)

15.491933384829666

In [8]:
# restra B
s.geometric_mean((4,70))   #(rating,reviews)

16.733200530681515

In [9]:
a=4
b=6

In [10]:
s.mean((a,b))  #arithmetic mean

5

In [11]:
s.geometric_mean((a,b))   #geometric mean

4.898979485566356

In [12]:
s.harmonic_mean((a,b))    #harmonic mean

4.8

# Median : center point of data

Types:

   1>Odd term median
   
   2> Even term median

# Demo:1

creating a sample data then sorting it into ascending order or descending order

In [13]:
x=[3,2,4,5,7,8,6,7,8,4]
print(type(x))

<class 'list'>


# Demo: 1.1

    Odd term median:
        
        formula: Median=((n+1)/2)th
        
        where:
            
            n=total no of values
            
            th=term

In [14]:
x=[3,2,4,5,7,8,6,7,8]    #odd term median

In [15]:
x.sort()

In [16]:
x

[2, 3, 4, 5, 6, 7, 7, 8, 8]

In [17]:
len(x)

9

# Demo: 1.2

 Even term median:
        
  formula: Median=((n/2)th+((n/2)+1)th)/2
        
        where:
            
            n=no of terms
            
            th=term

In [18]:
y=[0,1,2,3,4,5,6,7,8,9]   # odd term median
len(y)

10

In [19]:
z=[3,4,2,3,4,5,6,7,8,6]
z.sort()
print("Sorted data in ascending order :",z)
print("length :",len(z))

Sorted data in ascending order : [2, 3, 3, 4, 4, 5, 6, 6, 7, 8]
length : 10


In [20]:
def myMedian(n):
    if type(n)==tuple:
        n=list(n)
        n.sort()
    else:
        n.sort()
    print((n[(len(n)//2)]+n[((len(n)//2)+1)])/2)

In [21]:
myMedian(z)

5.5


In [22]:
def myMedian(n):
    if type(n)==tuple:
        n=list(n)
        n.sort()
    else:
        n.sort()
    print((n[(len(n)//2)-1]+n[((len(n)//2)+1)-1])/2)   #where we use -1 because indexing strt from 0 

In [23]:
myMedian(z)


4.5


In [24]:
z[1]

3

In [25]:
10//2

5

In [26]:
10/2

5.0

In [27]:
z=[3,4,2,4,3,8,5,6,7,6]
z_tuple=(3,4,2,3,8,7,5,6,6)
#z.sort()
print("Sorted data in ascending order :",z)
print("length :",len(z))

Sorted data in ascending order : [3, 4, 2, 4, 3, 8, 5, 6, 7, 6]
length : 10


In [28]:
def myMedian(n):
    if type(n)==tuple:
        n=list(n)
        n.sort()
    else:
        n.sort()
    print((n[(len(n)//2)-1]+n[((len(n)//2)+1)-1])/2) 

In [29]:
myMedian(z)
myMedian(z_tuple)

4.5
4.5


# Demo:1.2.1

even median and odd mediancalculation using statistics module of python

In [30]:
z=[3,4,2,3,4,5,6,7,8,6]

In [31]:
s.median(z)

4.5

In [32]:
y=[0,1,2,3,4,5,6,7,8,9]

In [33]:
s.median(x)

6

In [34]:
a=list((3,4,2,3,4,5,6,7,8,6))

In [35]:
a.sort()
a

[2, 3, 3, 4, 4, 5, 6, 6, 7, 8]

# Mode

help to get highest occuring value in the dataset

In [36]:
m=[2,3,3,4,4,5,6,6,7,8]

In [37]:
s.mode(m)

3

In [38]:
s.multimode(m)

[3, 4, 6]

# Quantiles:

statistics k andr ek method h quantile

In [39]:
x=[1,2,3,4,5,6,7,8]

In [40]:
s.quantiles(x)

[2.25, 4.5, 6.75]

In [41]:
y=[2,2,3,3.24,6,6.1,8,8.1]

In [43]:
q1,q2,q3=s.quantiles(y)

In [43]:
q1,q2,q3=s.quantiles(y)

In [44]:
q1

2.25

In [45]:
q2

4.62

In [46]:
q3


7.525

In [47]:
IQR=q1-q3

In [48]:
print(IQR)

-5.275


In [49]:
IQR2=abs(q3-q1)
print(IQR2)

5.275


# What is Trend?

In [50]:
dataset=[100,100000,200000,300000,320000]

In [51]:
q1,q2,q3=s.quantiles(dataset)
s.quantiles(dataset)

[50050.0, 200000.0, 310000.0]

In [52]:
Max_trend=q3+1.5*(IQR)
Max_trend

309992.0875

In [53]:
Min_trend=q1-1.5*IQR
Min_trend

50057.9125

In [55]:
filter_dataset=[]
for i in dataset:
    if Min_trend<i<Max_trend:
        filter_dataset.append(i)
print(filter_dataset)
    

[100000, 200000, 300000]


In [55]:
filter_dataset=[]
for i in dataset:
    if Min_trend<i<Max_trend:
        filter_dataset.append(i)
print(filter_dataset)
    

[100000, 200000, 300000]


# Name of the tools, hold structure data.
Database(sql database(strucutred data))

Html table

xml

wml(mobile appl work as xml called semi-structured data)

excel(semi-structured data)

ms access

etc..

# Unstructured data

a dataset which has no level of it column called unstructured.

tools: Numpy (2005) (numpy built in c++) 

Definition of array:-->An array contain similar type of data or values.

# Numpy

numpy has dual nature.

numpy has support of function and class but in some cases.

In [56]:
pip install numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,0])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [5]:
b=[1,2,3,4,5,6,7,8,9,0]
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [6]:
c=[1,'Krishna',1.2]
print(c)

[1, 'Krishna', 1.2]


In [7]:
d=np.array([1,'Krishna',1.2])
print(d)

['1' 'Krishna' '1.2']


In [8]:
e=np.array([1,2,3,4,5,1.2])
print(e)

[1.  2.  3.  4.  5.  1.2]


In [9]:
f=np.array([1,2,3,4,5,1.2,"krishna"])
print(f)

['1' '2' '3' '4' '5' '1.2' 'krishna']


In [10]:
f=np.array([1,2,3,4,5,1.2,"1"])
print(f)

['1' '2' '3' '4' '5' '1.2' '1']


In [11]:
f=np.array([1,2,3,4,5,1.2,"1"],dtype=np.int8)
print(f)

[1 2 3 4 5 1 1]


In [12]:
bin(10)

'0b1010'

In [13]:
64+32+16+8+4+2+1

127

In [14]:
f=np.array([1,2,3,4,5,6])
min(f)

1

In [15]:
f=np.array([1,2,3,4,5,1.2,"10.0"],dtype=np.int16)
print(f)

ValueError: invalid literal for int() with base 10: '10.0'

In [16]:
a="10.0"
int(a)

ValueError: invalid literal for int() with base 10: '10.0'

In [17]:
f=np.array([1,2,3,4,5,1.2,"10"],dtype=np.int8)
print(f)

[ 1  2  3  4  5  1 10]


In [18]:
f=np.array([1,2,3,4,5,1.2,"10.0"],dtype=np.float16)    # to convert list into int from str we will firstly convert into float then int
print(f)
g=np.array(f,dtype=np.int16)
print(g)

[ 1.   2.   3.   4.   5.   1.2 10. ]
[ 1  2  3  4  5  1 10]


In [19]:
h=np.array([1,2,3,4,5,6],dtype=np.str_)       # to convert list into string
print(h)

['1' '2' '3' '4' '5' '6']


# There are three types of array

1> Scaler --> a value which  has no(0)dimension. (jisme sirf magnitude hota h means no direction)

2>Vector(jisme magnitude direction dono ho)

3>Matrix

In [20]:
i=np.array([100])
print(i)
i                  # scaler array has no dimension or 0 dimension

[100]


array([100])

In [21]:
j=np.array([100,111,2,3,4,5,6])     # 1 dimensional array of vector
print(j)
j

[100 111   2   3   4   5   6]


array([100, 111,   2,   3,   4,   5,   6])

In [22]:
k=np.array([[1,2],[2,3]])     # 2 Dimensional array called matrix, diagonal matrix
print(k)
k
k.ndim

[[1 2]
 [2 3]]


2

In [23]:
l=np.array([[[100]]])
print(l)
l

[[[100]]]


array([[[100]]])

In [24]:
l=np.array([[[1,2],[2,3]],[[4,3],[8,9]]])    # 3 Dimensional array
print(l)

[[[1 2]
  [2 3]]

 [[4 3]
  [8 9]]]


In [25]:
l=np.array([[[1,2],[2,3]],[[4,3],[8,9]]])    
print(l)
l.ndim    # ndim is function which is no. of dimensions

[[[1 2]
  [2 3]]

 [[4 3]
  [8 9]]]


3

In [26]:
toy=np.array(['video game','trum card','contra','computer'])

In [27]:
toy

array(['video game', 'trum card', 'contra', 'computer'], dtype='<U10')

In [28]:
marks=np.array([[1,'A',75,50,70],[2,'B',33,40,80],[3,'C',90,100,91]])

In [29]:
marks

array([['1', 'A', '75', '50', '70'],
       ['2', 'B', '33', '40', '80'],
       ['3', 'C', '90', '100', '91']], dtype='<U11')

# Application of array:

0D --> 27(age)

1D --> to create list

2D --> to store tabular data

3D --> used to store image

4D --> to store video

In [30]:
demo1=np.array([i for i in range(100)])    #this is an array
print(demo1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [31]:
demo2=[i for i in range(100)]     #this is a list
print(demo2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


# Array is faster then list

In [32]:
import sys   # sys is third party library

In [33]:
sys.getsizeof(demo1)

512

In [34]:
sys.getsizeof(demo2)

920

In [35]:
import random

In [36]:
random.randint(1,10)    #it take only two parameter 

7

In [37]:
np.random.randint(1,10,5)       #in numpy randint take parameter,size,data type, strting nd ending values are inclusive

array([5, 5, 4, 1, 2])

In [38]:
np.random.randint(1,10,(3,2))  # 2D array

array([[6, 8],
       [1, 9],
       [8, 5]])

In [39]:
np.random.randint(1,10,(3,3,2))   #3D array,   (start,end,size of array)

array([[[8, 4],
        [7, 8],
        [6, 2]],

       [[7, 3],
        [2, 6],
        [5, 6]],

       [[9, 9],
        [4, 9],
        [9, 5]]])

In [40]:
np.random.randint(1,10,(4,3,3,2))   #4D array

array([[[[3, 2],
         [2, 4],
         [3, 7]],

        [[3, 1],
         [7, 1],
         [9, 6]],

        [[6, 9],
         [2, 5],
         [4, 5]]],


       [[[9, 9],
         [5, 9],
         [8, 4]],

        [[3, 5],
         [5, 5],
         [9, 1]],

        [[7, 9],
         [4, 1],
         [8, 1]]],


       [[[7, 2],
         [4, 9],
         [2, 2]],

        [[7, 8],
         [6, 9],
         [1, 8]],

        [[9, 3],
         [5, 4],
         [2, 9]]],


       [[[4, 3],
         [9, 4],
         [8, 2]],

        [[4, 8],
         [7, 1],
         [2, 3]],

        [[9, 2],
         [3, 3],
         [7, 3]]]])

In [41]:
np.random.randint(1,10,(5,4,3,3,2))   #5D array

array([[[[[4, 8],
          [6, 4],
          [8, 4]],

         [[7, 4],
          [7, 5],
          [8, 5]],

         [[3, 8],
          [2, 4],
          [3, 2]]],


        [[[6, 1],
          [4, 2],
          [9, 5]],

         [[4, 2],
          [1, 7],
          [2, 2]],

         [[5, 7],
          [4, 4],
          [8, 6]]],


        [[[9, 7],
          [5, 5],
          [4, 9]],

         [[3, 6],
          [6, 8],
          [1, 6]],

         [[1, 1],
          [7, 2],
          [9, 6]]],


        [[[8, 6],
          [1, 6],
          [8, 4]],

         [[3, 2],
          [3, 4],
          [7, 8]],

         [[9, 5],
          [1, 7],
          [1, 6]]]],



       [[[[2, 2],
          [6, 1],
          [3, 1]],

         [[7, 2],
          [5, 1],
          [3, 5]],

         [[9, 7],
          [7, 1],
          [8, 6]]],


        [[[7, 8],
          [1, 1],
          [7, 1]],

         [[1, 8],
          [5, 5],
          [5, 8]],

         [[1, 1],
          [1, 2],


In [42]:
np.random.uniform(0,10,10)       
#it provide randomly float values,
#its strting value (inclusive), ending value (exclusive)

array([3.76115074, 1.78662447, 3.10880884, 5.31441773, 0.55200473,
       7.97129434, 5.29970098, 5.11426328, 0.73782104, 5.24081466])

In [43]:
np.random.randint(1,10,10) 
#it provide randomly integer values
#intial value(inclusive),end value(enclusive), size

array([7, 4, 9, 9, 1, 8, 6, 9, 9, 1])

In [44]:
np.random.randint(1,10,(3,2),dtype=np.int16) 

array([[2, 5],
       [8, 8],
       [3, 5]], dtype=int16)

In [45]:
x=np.random.randint(1,10,(3,2))

In [46]:
x

array([[1, 5],
       [3, 7],
       [5, 2]])

In [47]:
np.array(x,dtype=np.float16)    #converting randint into float

array([[1., 5.],
       [3., 7.],
       [5., 2.]], dtype=float16)

In [48]:
np.linspace(1,10,10)    #function, uniformly euidistance data create using linspace b/w two points
#strting nd ending values are inclusive
#size can be increases

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
np.linspace(0.5,10,20) 

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [50]:
np.linspace(1,11,21,dtype=np.int16)   # it convert float into int

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10, 11], dtype=int16)

In [51]:
range(10)

range(0, 10)

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape:  array_name.reshape((size of array))

* it is function which on numpy
* no need of permanent changes in array we use reshape

# Resize:  array_name.resize()

* when we need permanent changes in array_name 

In [126]:
array_name=np.array([1,2,3,4,5,6,7,8,9,0])
array_name

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [131]:
array_name.reshape((2,5))    #order is C bydefault

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [128]:
array_name

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [129]:
array_name.reshape((2,5),order='C')

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [130]:
array_name.reshape((2,5),order='F')

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [138]:
array_name.resize((2,5))  # it changes our base array array_name

In [139]:
array_name

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [140]:
array_name.resize((5,2))

In [141]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [143]:
array_name.resize((4,2),refcheck=False)

In [144]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [146]:
array_name.resize((6,2),refcheck=False)   # when size is large then actual array it will provide zero
array_name  

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [0, 0],
       [0, 0]])

In [147]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [0, 0],
       [0, 0]])

In [142]:
X=np.random.randint(1,10,(3,2))

In [54]:
X

array([[7, 3],
       [4, 7],
       [4, 5]])

In [55]:
y=X.flatten()    # flatten is define as converting any dimensional array into 1D array
y

array([7, 3, 4, 7, 4, 5])

In [66]:
X.resize((2,3))
#resize do permanent changes into existing array

In [67]:
X

array([[7, 3, 4],
       [7, 4, 5]])

In [68]:
z=np.random.randint(1,10,(3,2))

In [69]:
z

array([[4, 3],
       [4, 2],
       [7, 3]])

In [70]:
z.flatten()

array([4, 3, 4, 2, 7, 3])

In [71]:
z.reshape((2,3))

array([[4, 3, 4],
       [2, 7, 3]])

In [72]:
z

array([[4, 3],
       [4, 2],
       [7, 3]])

In [73]:
z.reshape((2,3),order='F')
#reshape not do permanent changes into array
#F is a language called fortran it is use to flatten

array([[4, 7, 2],
       [4, 3, 3]])

In [74]:
z.reshape((2,3),order='C')

array([[4, 3, 4],
       [2, 7, 3]])

In [75]:
array1=np.arange(16)

In [76]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
array1.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
array1.reshape((3,2))

ValueError: cannot reshape array of size 16 into shape (3,2)

In [81]:
array1.reshape((2,-1))
#when we don't know the columns put it -1
#it also allow in single bracket

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [84]:
array1.reshape(-1,2)
#when we don't know the rows put it -1
#it also allow in single bracket

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [83]:
array1.reshape((-1,2),order='F')

array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [85]:
array1.reshape((-1,-1))

ValueError: can only specify one unknown dimension

In [87]:
len(array1)

16

In [89]:
len((array1.reshape(2,8)).flatten())

16

In [90]:
a=array1.reshape(2,8)
b=a.flatten()
len(b)

16

In [99]:
a=np.arange(16)

In [100]:
a=a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [103]:
a.resize((3,4),refcheck=False)   #refcheck use to resize array on the size given and remaining values left 

In [104]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Broadcasting

In [105]:
list1=[1,2,3,4,5]
list2=[3,4,5,6,7]

In [110]:
for i,j in zip(list1,list2):
    print(i,j)

1 3
2 4
3 5
4 6
5 7


In [111]:
for i,j in zip(list1,list2):
    print(i+j)

4
6
8
10
12


In [114]:
#list broadcasting using for loop rule1:
empty=[]
for i,j in zip(list1,list2):
    empty.append(i+j)

In [113]:
empty

[4, 6, 8, 10, 12]

In [116]:
#list broadcasting using for loop rule2:
empty2=[i+j for i,j in zip(list1,list2)]
empty2

[4, 6, 8, 10, 12]

In [106]:
list1+list2

[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]

In [107]:
array1=np.array([1,2,3,4,5])
array2=np.array([2,3,4,5,6])

In [108]:
array1+array2

array([ 3,  5,  7,  9, 11])

In [117]:
np.concatenate((array1,array2))

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [118]:
array1*array2

array([ 2,  6, 12, 20, 30])

In [119]:
array1/array2

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [122]:
array1//array2   #floor division

array([0, 0, 0, 0, 0])

In [123]:
np.round(array1/array2,decimals=2)

array([0.5 , 0.67, 0.75, 0.8 , 0.83])

In [124]:
a=np.random.uniform(1,10,10)

In [125]:
np.round(a,2)

array([7.29, 2.68, 4.51, 3.59, 7.13, 1.31, 1.63, 7.72, 7.28, 5.77])

# vstack and hstack

vertical stack {vstack}   and   horizontal stack {hstack}

* vstack --> is function jiske andar array pass krte h tuple ki form me

in 2D vstack columns values must be same and have same dimensions

In [148]:
a=np.random.randint(1,10,(3,2))    # 2D array
a

array([[9, 9],
       [4, 4],
       [9, 6]])

In [149]:
b=np.random.randint(1,10,(2,2))   # 2D array
b

array([[1, 9],
       [6, 6]])

In [155]:
np.vstack((a,b))     # 2D array

array([[9, 9],
       [4, 4],
       [9, 6],
       [1, 9],
       [6, 6]])

# 3D array vstacking

in 3D array vstacking we must remember the row,column

in 4D array vstack we must remember the dimension,row,column

In [151]:
c=np.random.randint(1,10,(3,2,2))   #(3,2,2) defines the dimension{3}, row{2}, column{2}
c

array([[[8, 5],
        [1, 1]],

       [[6, 5],
        [6, 8]],

       [[4, 5],
        [1, 6]]])

In [152]:
d=np.random.randint(1,10,(4,2,2))
d

array([[[6, 7],
        [6, 9]],

       [[9, 1],
        [2, 6]],

       [[3, 5],
        [7, 7]],

       [[3, 5],
        [5, 4]]])

In [153]:
np.vstack((c,d))

array([[[8, 5],
        [1, 1]],

       [[6, 5],
        [6, 8]],

       [[4, 5],
        [1, 6]],

       [[6, 7],
        [6, 9]],

       [[9, 1],
        [2, 6]],

       [[3, 5],
        [7, 7]],

       [[3, 5],
        [5, 4]]])

# hstack 

horizontal stacking


in 2D hstack we must remember the row  and have same dimensions

In [156]:
e=np.random.randint(1,10,(2,3))   # 2D 
e

array([[8, 3, 3],
       [8, 3, 3]])

In [157]:
f=np.random.randint(1,10,(2,10))   # 2D 
f

array([[9, 4, 2, 4, 3, 7, 7, 2, 9, 9],
       [7, 1, 1, 7, 5, 1, 1, 4, 1, 5]])

In [158]:
np.hstack((e,f))

array([[8, 3, 3, 9, 4, 2, 4, 3, 7, 7, 2, 9, 9],
       [8, 3, 3, 7, 1, 1, 7, 5, 1, 1, 4, 1, 5]])

# 3D array hstacking

in 3D array vstacking we must remember the row,column

In [159]:
g=np.random.randint(1,10,(3,2,2))   
g

array([[[3, 8],
        [2, 6]],

       [[1, 3],
        [3, 9]],

       [[1, 7],
        [8, 3]]])

In [161]:
h=np.random.randint(1,10,(3,2,2))   
h

array([[[5, 2],
        [3, 3]],

       [[3, 3],
        [1, 7]],

       [[8, 5],
        [5, 7]]])

In [162]:
np.hstack((g,h))

array([[[3, 8],
        [2, 6],
        [5, 2],
        [3, 3]],

       [[1, 3],
        [3, 9],
        [3, 3],
        [1, 7]],

       [[1, 7],
        [8, 3],
        [8, 5],
        [5, 7]]])

In [163]:
i=np.random.randint(1,10,10)
i

array([3, 2, 1, 9, 2, 7, 7, 6, 4, 2])

In [164]:
np.min(i)

1

In [165]:
np.max(i)

9

In [166]:
np.sum(i)

43

In [167]:
np.mean(i)

4.3

In [169]:
np.std(i)   #std is standard deviation

2.6095976701399777

In [170]:
i

array([3, 2, 1, 9, 2, 7, 7, 6, 4, 2])

In [174]:
j=np.random.randint(1,10,(2,10))
j

array([[1, 2, 6, 7, 2, 4, 6, 8, 5, 6],
       [5, 2, 1, 8, 1, 5, 3, 6, 6, 4]])

In [176]:
k=np.array([[1,2,3,4,5],[6,7,8,9,0]])
k

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [172]:
np.min(j)

2

In [177]:
np.min(k)

0

In [178]:
np.max(k)

9

In [179]:
np.mean(k)

4.5

In [180]:
np.std(k)

2.8722813232690143

In [183]:
np.argmin(k)   #argmin provide index value of min value

9

In [184]:
k.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [185]:
k

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [186]:
np.argmax(k)

8

In [190]:
np.argmax(k,axis=1)   # it detect larger value's index row-wise
# axis=1 means checking the value row wise and max value will provided by index no.

array([4, 3], dtype=int64)

In [189]:
np.argmax(k,axis=0)  
# axis0 means checking the value column wise and max value result by index no.

array([1, 1, 1, 1, 0], dtype=int64)

In [188]:
k

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [191]:
np.sum(k)

45

In [201]:
np.sum(k,axis=1)

array([15, 30])

In [202]:
print("sum of all value in array:",np.sum(k))
print("sum of all value according to row-wise in array:",np.sum(k,axis=1))

sum of all value in array: 45
sum of all value according to row-wise in array: [15 30]


In [203]:
np.sum(k,axis=0)

array([ 7,  9, 11, 13,  5])

In [204]:
print("sum of all value in array:",np.sum(k))
print("sum of all value according to column-wise in array:",np.sum(k,axis=0))

sum of all value in array: 45
sum of all value according to column-wise in array: [ 7  9 11 13  5]


# argmin   and  argmax

In [205]:
a=[3,4,5,2,5,4,7,4,2]

In [206]:
max(a)

7

In [207]:
def new(arg):
    arg.sort()
    return arg

In [208]:
new(a)

[2, 2, 3, 4, 4, 4, 5, 5, 7]

In [222]:
def new(arg):     #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])    #1234
    counter=-1
    drg=arg.copy()   #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])   #2345
    drg.sort()       #[14, 21, 32, 33, 37, 67, 77, 82, 84, 92]     #2345
    d=drg[-1]    #92
    for i in a:     #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])    #1234
        counter+=1
        if i==d:      #i=92   d=92   #i==d   True
            break
    return counter    #counter count the index value

In [223]:
new(a)

8

In [220]:
d=np.random.randint(1,100,10)
d

array([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])

In [221]:
new(d)

8

In [224]:
d.sort()
d

array([14, 21, 32, 33, 37, 67, 77, 82, 84, 92])

In [226]:
d=[14, 32, 82, 92, 21, 77, 84, 33, 67, 37]

In [227]:
np.argmax(d)

3

In [228]:
np.argmin(d)

0

In [229]:
def old(arg):     #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])    #1234
    counter=-1
    drg=arg.copy()   #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])   #2345
    drg.sort()       #[14, 21, 32, 33, 37, 67, 77, 82, 84, 92]     #2345
    d=drg[0]    #92
    for i in a:     #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])    #1234
        counter+=1
        if i==d:      #i=92   d=92   #i==d   True
            break
    return counter 

In [230]:
old(d)

8

In [231]:
d

[14, 32, 82, 92, 21, 77, 84, 33, 67, 37]

In [233]:
e=np.reshape(d,(5,2))
e

array([[14, 32],
       [82, 92],
       [21, 77],
       [84, 33],
       [67, 37]])

In [234]:
np.argmin(e)

0

In [235]:
np.argmax(e)

3

In [239]:
def old(arg):     #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])    #1234
    counter=-1
    drg=arg.copy() #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])   #2345
    a=arg.ndim
    if a<2:
        pass
    else:
        drg=drg.flatten()
        arg=arg.flatten()
    drg.sort()       #[14, 21, 32, 33, 37, 67, 77, 82, 84, 92]     #2345
    d=drg[0]    #92
    for i in arg:     #([14, 32, 82, 92, 21, 77, 84, 33, 67, 37])    #1234
        counter+=1
        if i==d:      #i=92   d=92   #i==d   True
            break
    return counter 

In [236]:
a=np.array([[2,3],[3,5]])

In [237]:
a.sort()

In [238]:
a.flatten()

array([2, 3, 3, 5])

In [240]:
old(a)

0

In [257]:
a=np.random.randint(1,10,8)
a

array([3, 1, 7, 3, 8, 3, 1, 5])

In [258]:
b=np.reshape(a,(1,2,4))
b

array([[[3, 1, 7, 3],
        [8, 3, 1, 5]]])

In [259]:
b[0][0]

array([3, 1, 7, 3])

In [260]:
b[0][0][0]

3

In [261]:
old(b)

1

In [264]:
np.argmin(b,axis=0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [265]:
b=np.reshape(a,(2,4))
b

array([[3, 1, 7, 3],
       [8, 3, 1, 5]])

In [266]:
np.argmin(b,axis=1)

array([1, 2], dtype=int64)

In [267]:
np.argmin(b,axis=0)

array([0, 0, 1, 0], dtype=int64)

# Sorting

In [281]:
a=np.random.randint(1,10,10)
a

array([7, 2, 8, 9, 5, 8, 5, 7, 1, 2])

In [277]:
a.sort()

In [278]:
a

array([1, 1, 2, 2, 3, 4, 4, 8, 9, 9])

In [282]:
b=np.resize(a,(5,2))
b

array([[7, 2],
       [8, 9],
       [5, 8],
       [5, 7],
       [1, 2]])

In [285]:
b.sort(axis=0)   #column wise sorting ki h bydefault row-wise krta
b

array([[1, 2],
       [2, 7],
       [5, 7],
       [5, 8],
       [8, 9]])

In [287]:
c=b.flatten()
c

array([1, 2, 2, 7, 5, 7, 5, 8, 8, 9])

In [288]:
np.square(c)

array([ 1,  4,  4, 49, 25, 49, 25, 64, 64, 81])

In [289]:
c

array([1, 2, 2, 7, 5, 7, 5, 8, 8, 9])

In [293]:
f=np.sqrt(c)
f

array([1.        , 1.41421356, 1.41421356, 2.64575131, 2.23606798,
       2.64575131, 2.23606798, 2.82842712, 2.82842712, 3.        ])

In [296]:
g=np.round(f,decimals=2)
g

array([1.  , 1.41, 1.41, 2.65, 2.24, 2.65, 2.24, 2.83, 2.83, 3.  ])

In [299]:
np.array(g,dtype=np.int16)     #change in datatype

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 3], dtype=int16)

In [300]:
np.tan(90)

-1.995200412208242

In [306]:
a=np.array([i for i in range(10)])
print(a)
np.log(a)          #inf means infinte

[0 1 2 3 4 5 6 7 8 9]


C:\Users\Dell\AppData\Local\Temp\ipykernel_1740\50215680.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a)          #inf means infinte


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [307]:
b=np.array(np.arange(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [308]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [309]:
np.tan(b)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [310]:
np.log10(b)

C:\Users\Dell\AppData\Local\Temp\ipykernel_1740\3416214235.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(b)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [311]:
np.cos(b)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [314]:
np.arange(1,7)
np.resize(np.arange(1,7),(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [319]:
a=np.arange(1,7)
b=np.resize(a,(2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [320]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [322]:
b.T  #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [326]:
b.sum()   #class p work krra

21

In [327]:
np.sum(b)     #function p work krra

21

In [328]:
b.min()

1

In [329]:
np.min(b)

1